name: CI on  preprod pull request
on:
  pull_request:
    branches:
      - preprod
jobs:
  Deploy:
    name: Lint
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
