name: Deploy website to heroku
on:
  push:
    branches:
      - preprod
jobs:
  Deploy:
    name: Lint, Build and Deploy
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - name: eslint
        uses: icrawl/action-eslint@v1
      - name: deploy heroku
        uses: akhileshns/heroku-deploy@v3.5.7 # This is the action
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
